Fixed a bug where passing an `int` or `list` via the `hdus` keyword argument to
`~sunpy.io.fits.read` threw an exception because the list of HDU objects was no longer
of type `~astropy.io.fits.hdu.HDUList`.
